### ISSUE TITLE
Implement DTLS

### ISSUE THREAD

**Issue by GiedriusM** [punica/punica#8]
Use/build wakaama lib with DTLS. Configure connection credentials based data loaded from database/json file. Reject other connections. Add DTLS client tests.

**Comment by taubel** [comment]
DTLS security, as defined by LWM2M 1.1 specification and RFC7925 has the following requirements and recommendations:

- All communication parties MUST perform mutual authentication and data encryption [SPEC 5.1]

- All devices MUST have unique security credentials [SPEC 5.2.1]

- Security state, session keys, sequence numbers, initialization vectors and other security parameters SHOULD be saved in secure storage for devices which work with sleep cycles [SPEC 5.2.1]

**Suggested cipher suites:**

If using pre-shared keys, then the server MUST support: [SPEC 5.2.8.1]

- TLS_PSK_WITH_AES_128_CCM_8

- TLS_PSK_WITH_AES_128_CBC_SHA256

If using raw public keys (NOT SUPPORTED IN MBEDTLS), then the server MUST support: [SPEC 5.2.8.2]

- TLS_ECDHE_ECDSA_WITH_AES_128_CCM_8

- TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256

If using x509 certificates, then the server MUST support: [SPEC 5.2.8.3]

- TLS_ECDHE_ECDSA_WITH_AES_128_CCM_8

- TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256

_Use of CBC_SHA256 cipher suites is not recommended because of security risks [SPEC 5.2.8.*]_

**Additional requirements for certificate based authentication:**

- During CoAP registration, the endpoint name provided by the client MUST be an EUI-64 and be verified against the identifier used during the handshake (stored in the certificate CN field) [SPEC 5.2.6 and RFC7925 4.4.2]

- Certificate generation MUST use the "secp256r1" elliptical curve (defined as "prime256v1" in openssl) [SPEC 5.2.3]

- All devices MUST have a RTC for certificate expiration time validation [SPEC 5.2.8.5]

**Comment by taubel** [comment]
Clients and Servers MUST support PSK keys of up to 64 bytes in length

**Comment by GiedriusM** [comment]
Resolved by #45
